CXX=g++

ex19: ex19.cpp MyFirstAbstractClass.h MyFirstAbstractClass.cpp MyFirstChildClass.h MyFirstChildClass.cpp
	$(CXX) ex19.cpp MyFirstAbstractClass.cpp MyFirstChildClass.cpp -o ex19

clean:
	rm -f ex19 *~
